# Generated by Django 2.1.7 on 2019-03-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('usage', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('agreement', models.BooleanField(default=False)),
                ('permission', models.IntegerField(choices=[(1, 'disapproval'), (2, 'approval')], default=1)),
                ('password', models.CharField(max_length=100)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
