# Generated by Django 2.1.7 on 2019-03-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaython', '0002_applicant_agree_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='agree_contents',
        ),
        migrations.AddField(
            model_name='applicant',
            name='I_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='agreement',
            field=models.TextField(default='학부 교육용 서버는 학생과 교원이 교육과 연구를 위한 목적으로 사용되어야 하며, 그 이외의 목적으로 인한 사용은 제한됩니다. 학부 서버는 여러 학생과 교수가 공동으로 사용하는 장비로,  각 사용자는 서버 관리자의 운영에 적극 협조해야 합니다. 다른 사용자의 사용을 방해하는 행위나 다른 사용자의 보안을 해치는 행위, 지속적인 오사용으로 서버 운영에 방해가 있는 경우, 혹은 2개월 이상 사용이 없을 경우 예고 없이 계정과 계정에 속한 파일이 삭제 될 수 있습니다.', max_length=300),
        ),
    ]
